services:
  bot:
    build: .
    restart: unless-stopped
    depends_on: [db]
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/vieribot
      - DISCORD_TOKEN
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
